import View from "./view";
type Stream = Set<any>;
type BeforeUpdatedCallback = (fromEl: Element, toEl: Element) => void;
type AfterAddedCallback = (el: Node) => void;
type AfterUpdatedCallback = (el: Element) => void;
type AfterPhxChildAddedCallback = (el: Element) => void;
type AfterDiscardedCallback = (el: Node) => void;
type AfterTransitionsDiscardedCallback = (els: Element[]) => void;
export default class DOMPatch {
    private view;
    private liveSocket;
    private container;
    private rootID;
    private html;
    private streams;
    private streamInserts;
    private streamComponentRestore;
    private targetCID;
    private pendingRemoves;
    private phxRemove;
    private targetContainer;
    private beforeUpdatedCallbacks;
    private afterAddedCallbacks;
    private afterUpdatedCallbacks;
    private afterPhxChildAddedCallbacks;
    private afterDiscardedCallbacks;
    private afterTransitionsDiscardedCallbacks;
    private withChildren;
    private undoRef;
    constructor(view: View, container: Element, html: string | Node, streams: Set<Stream>, targetCID: number | null, opts?: {
        withChildren?: boolean;
        undoRef?: number;
    });
    beforeUpdated(callback: BeforeUpdatedCallback): void;
    afterAdded(callback: AfterAddedCallback): void;
    afterUpdated(callback: AfterUpdatedCallback): void;
    afterPhxChildAdded(callback: AfterPhxChildAddedCallback): void;
    afterDiscarded(callback: AfterDiscardedCallback): void;
    afterTransitionsDiscarded(callback: AfterTransitionsDiscardedCallback): void;
    markPrunableContentForRemoval(): void;
    perform(isJoinPatch: any): boolean;
    private trackBeforeUpdated;
    private trackAfterAdded;
    private trackAfterUpdated;
    private trackAfterPhxChildAdded;
    private trackAfterDiscarded;
    private trackAfterTransitionsDiscarded;
    private onNodeDiscarded;
    private maybePendingRemove;
    private removeStreamChildElement;
    private getStreamInsert;
    private setStreamRef;
    private maybeReOrderStream;
    private moveOrInsertBefore;
    private maybeLimitStream;
    private transitionPendingRemoves;
    private isChangedSelect;
    private skipCIDSibling;
    private maybeCloneLockedElement;
    private copyNestedPrivateLock;
    private indexOf;
    private teleport;
    private handleRuntimeHook;
}
export {};
